const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  WHATSAPP_DISCONNECTED: 'WHATSAPP_DISCONNECTED',
  WHATSAPP_STATUS_UNAVAILABLE: 'WHATSAPP_STATUS_UNAVAILABLE',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};

module.exports = {
  ERROR_CODES
};
